### ISSUE TITLE
不起作用,脚本报错了

### ISSUE THREAD

**Issue by XXAndroid** [fluttercandies/no-free-usage-action#9]
我的项目是非dart项目,脚本执行爆了如下的错误:
```
Could not find a file named "pubspec.yaml" in "/github/workspace".
Error: Error when reading 'bin/main.dart': No such file or directory
```
![image](https://user-images.githubusercontent.com/37856379/92621201-1bc51980-f2f6-11ea-985c-c7bc56e28e8c.png)
如果项目是dart项目,但是是flutter项目,又爆了如下错误:
```
Resolving dependencies...
Because flutter_xupdate requires the Flutter SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `pub get`.
Error: Error when reading 'bin/main.dart': No such file or directory
```
![image](https://user-images.githubusercontent.com/37856379/92625082-d8b97500-f2fa-11ea-91f8-7a9757a215d8.png)
难道项目必须是纯dart项目???

脚本编辑如下:

```
name: No Free usage issue checker  # Action名字。可以自定义
on:
  issues:
    types: [opened, reopened]  # 在issue打开和重新打开时调用

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check issue actor  # 步骤名字。可以自定义。
        uses: fluttercandies/no-free-usage-action@master  # 使用最新版本的action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 由GitHub提供的临时Token，必须在此处进行传递，且必须为这个值。
          forked: '--no-forked'
```
